services:
  - type: web
    name: boutique-ayla
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx next start -H 0.0.0.0 -p $PORT
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: SELLER_EMAIL
        value: djohar@boutiqueayla.dz
      - key: SELLER_PASSWORD
        sync: false
