import type { Wilaya } from "./types";

const c = (...names: string[]) => names;

export const wilayas: Wilaya[] = [
  { code: "01", name: "Adrar", home: 900, stopdesk: 650, delay: "5–7 jours", zone: "Sud", communes: c("Adrar", "Reggane", "Timimoun", "Aoulef") },
  { code: "02", name: "Chlef", home: 550, stopdesk: 400, delay: "2–4 jours", zone: "Ouest", communes: c("Chlef", "Ténès", "Oued Fodda", "Boukadir") },
  { code: "03", name: "Laghouat", home: 700, stopdesk: 500, delay: "3–5 jours", zone: "Sud", communes: c("Laghouat", "Aflou", "Ksar El Hirane") },
  { code: "04", name: "Oum El Bouaghi", home: 600, stopdesk: 450, delay: "2–4 jours", zone: "Est", communes: c("Oum El Bouaghi", "Aïn Beïda", "Aïn M'lila") },
  { code: "05", name: "Batna", home: 600, stopdesk: 450, delay: "2–4 jours", zone: "Est", communes: c("Batna", "Barika", "Arris", "Merouana") },
  { code: "06", name: "Béjaïa", home: 550, stopdesk: 400, delay: "2–3 jours", zone: "Centre", communes: c("Béjaïa", "Akbou", "Kherrata", "El Kseur") },
  { code: "07", name: "Biskra", home: 650, stopdesk: 480, delay: "3–5 jours", zone: "Sud", communes: c("Biskra", "Tolga", "Ouled Djellal", "Sidi Okba") },
  { code: "08", name: "Béchar", home: 900, stopdesk: 650, delay: "5–7 jours", zone: "Sud", communes: c("Béchar", "Abadla", "Kenadsa") },
  { code: "09", name: "Blida", home: 450, stopdesk: 300, delay: "24–48 h", zone: "Centre", communes: c("Blida", "Boufarik", "Larbaa", "Bougara") },
  { code: "10", name: "Bouira", home: 500, stopdesk: 350, delay: "2–3 jours", zone: "Centre", communes: c("Bouira", "Lakhdaria", "Sour El Ghozlane") },
  { code: "11", name: "Tamanrasset", home: 1200, stopdesk: 900, delay: "6–9 jours", zone: "Sud", communes: c("Tamanrasset", "In Salah", "Tazrouk") },
  { code: "12", name: "Tébessa", home: 700, stopdesk: 500, delay: "3–5 jours", zone: "Est", communes: c("Tébessa", "Bir El Ater", "Cheria") },
  { code: "13", name: "Tlemcen", home: 650, stopdesk: 450, delay: "3–4 jours", zone: "Ouest", communes: c("Tlemcen", "Maghnia", "Remchi", "Ghazaouet") },
  { code: "14", name: "Tiaret", home: 600, stopdesk: 430, delay: "2–4 jours", zone: "Ouest", communes: c("Tiaret", "Frenda", "Sougueur") },
  { code: "15", name: "Tizi Ouzou", home: 500, stopdesk: 350, delay: "2–3 jours", zone: "Centre", communes: c("Tizi Ouzou", "Azazga", "Draâ Ben Khedda", "Boghni") },
  { code: "16", name: "Alger", home: 400, stopdesk: 250, delay: "24–48 h", zone: "Centre", communes: c("Hydra", "Bab Ezzouar", "Bir Mourad Raïs", "Kouba", "Chéraga", "Dar El Beïda") },
  { code: "17", name: "Djelfa", home: 650, stopdesk: 480, delay: "3–4 jours", zone: "Centre", communes: c("Djelfa", "Aïn Oussera", "Hassi Bahbah") },
  { code: "18", name: "Jijel", home: 600, stopdesk: 430, delay: "2–4 jours", zone: "Est", communes: c("Jijel", "El Milia", "Taher") },
  { code: "19", name: "Sétif", home: 550, stopdesk: 400, delay: "2–3 jours", zone: "Est", communes: c("Sétif", "El Eulma", "Aïn Oulmene", "Bougaa") },
  { code: "20", name: "Saïda", home: 650, stopdesk: 470, delay: "3–4 jours", zone: "Ouest", communes: c("Saïda", "Aïn El Hadjar", "Youb") },
  { code: "21", name: "Skikda", home: 600, stopdesk: 430, delay: "2–4 jours", zone: "Est", communes: c("Skikda", "Collo", "Azzaba", "El Harrouch") },
  { code: "22", name: "Sidi Bel Abbès", home: 600, stopdesk: 430, delay: "2–4 jours", zone: "Ouest", communes: c("Sidi Bel Abbès", "Telagh", "Sfisef") },
  { code: "23", name: "Annaba", home: 600, stopdesk: 430, delay: "2–4 jours", zone: "Est", communes: c("Annaba", "El Bouni", "Seraïdi") },
  { code: "24", name: "Guelma", home: 600, stopdesk: 450, delay: "2–4 jours", zone: "Est", communes: c("Guelma", "Oued Zenati", "Bouchegouf") },
  { code: "25", name: "Constantine", home: 550, stopdesk: 400, delay: "2–3 jours", zone: "Est", communes: c("Constantine", "El Khroub", "Hamma Bouziane", "Ali Mendjeli") },
  { code: "26", name: "Médéa", home: 500, stopdesk: 350, delay: "2–3 jours", zone: "Centre", communes: c("Médéa", "Berrouaghia", "Ksar El Boukhari") },
  { code: "27", name: "Mostaganem", home: 550, stopdesk: 400, delay: "2–3 jours", zone: "Ouest", communes: c("Mostaganem", "Aïn Tédelès", "Sidi Ali") },
  { code: "28", name: "M'Sila", home: 600, stopdesk: 450, delay: "2–4 jours", zone: "Centre", communes: c("M'Sila", "Bou Saâda", "Sidi Aïssa") },
  { code: "29", name: "Mascara", home: 600, stopdesk: 430, delay: "2–4 jours", zone: "Ouest", communes: c("Mascara", "Sig", "Mohammadia") },
  { code: "30", name: "Ouargla", home: 800, stopdesk: 580, delay: "4–6 jours", zone: "Sud", communes: c("Ouargla", "Touggourt", "Hassi Messaoud") },
  { code: "31", name: "Oran", home: 550, stopdesk: 400, delay: "2–3 jours", zone: "Ouest", communes: c("Oran", "Bir El Djir", "Es Senia", "Aïn El Turk") },
  { code: "32", name: "El Bayadh", home: 800, stopdesk: 580, delay: "4–6 jours", zone: "Sud", communes: c("El Bayadh", "Bougtob", "Brezina") },
  { code: "33", name: "Illizi", home: 1200, stopdesk: 900, delay: "6–9 jours", zone: "Sud", communes: c("Illizi", "Djanet", "In Amenas") },
  { code: "34", name: "Bordj Bou Arreridj", home: 550, stopdesk: 400, delay: "2–3 jours", zone: "Est", communes: c("Bordj Bou Arreridj", "Ras El Oued", "Mansoura") },
  { code: "35", name: "Boumerdès", home: 450, stopdesk: 300, delay: "24–48 h", zone: "Centre", communes: c("Boumerdès", "Bordj Menaïel", "Dellys", "Thénia") },
  { code: "36", name: "El Tarf", home: 650, stopdesk: 470, delay: "3–4 jours", zone: "Est", communes: c("El Tarf", "El Kala", "Besbes") },
  { code: "37", name: "Tindouf", home: 1100, stopdesk: 800, delay: "6–8 jours", zone: "Sud", communes: c("Tindouf", "Oum El Assel") },
  { code: "38", name: "Tissemsilt", home: 600, stopdesk: 430, delay: "2–4 jours", zone: "Ouest", communes: c("Tissemsilt", "Theniet El Had", "Bordj Bounaama") },
  { code: "39", name: "El Oued", home: 750, stopdesk: 550, delay: "4–6 jours", zone: "Sud", communes: c("El Oued", "Guemar", "Debila") },
  { code: "40", name: "Khenchela", home: 650, stopdesk: 480, delay: "3–5 jours", zone: "Est", communes: c("Khenchela", "Kais", "Chechar") },
  { code: "41", name: "Souk Ahras", home: 650, stopdesk: 470, delay: "3–4 jours", zone: "Est", communes: c("Souk Ahras", "Sedrata", "Taoura") },
  { code: "42", name: "Tipaza", home: 450, stopdesk: 300, delay: "24–48 h", zone: "Centre", communes: c("Tipaza", "Cherchell", "Kolea", "Hadjout") },
  { code: "43", name: "Mila", home: 600, stopdesk: 430, delay: "2–4 jours", zone: "Est", communes: c("Mila", "Chelghoum Laïd", "Ferdjioua") },
  { code: "44", name: "Aïn Defla", home: 550, stopdesk: 400, delay: "2–3 jours", zone: "Centre", communes: c("Aïn Defla", "Khemis Miliana", "El Attaf") },
  { code: "45", name: "Naâma", home: 800, stopdesk: 580, delay: "4–6 jours", zone: "Sud", communes: c("Naâma", "Mécheria", "Aïn Sefra") },
  { code: "46", name: "Aïn Témouchent", home: 600, stopdesk: 430, delay: "2–4 jours", zone: "Ouest", communes: c("Aïn Témouchent", "Beni Saf", "Hammam Bouhadjar") },
  { code: "47", name: "Ghardaïa", home: 750, stopdesk: 550, delay: "4–5 jours", zone: "Sud", communes: c("Ghardaïa", "Metlili", "Berriane", "El Meniaa") },
  { code: "48", name: "Relizane", home: 550, stopdesk: 400, delay: "2–3 jours", zone: "Ouest", communes: c("Relizane", "Oued Rhiou", "Mazouna") },
  { code: "49", name: "Timimoun", home: 950, stopdesk: 700, delay: "5–7 jours", zone: "Sud", communes: c("Timimoun", "Aougrout", "Charouine") },
  { code: "50", name: "Bordj Badji Mokhtar", home: 1300, stopdesk: 980, delay: "7–10 jours", zone: "Sud", communes: c("Bordj Badji Mokhtar", "Timiaouine") },
  { code: "51", name: "Ouled Djellal", home: 700, stopdesk: 500, delay: "3–5 jours", zone: "Sud", communes: c("Ouled Djellal", "Sidi Khaled", "Ras El Miad") },
  { code: "52", name: "Béni Abbès", home: 1000, stopdesk: 750, delay: "6–8 jours", zone: "Sud", communes: c("Béni Abbès", "Igli", "El Ouata") },
  { code: "53", name: "In Salah", home: 1100, stopdesk: 820, delay: "6–8 jours", zone: "Sud", communes: c("In Salah", "In Ghar", "Foggaret Ezzaouia") },
  { code: "54", name: "In Guezzam", home: 1400, stopdesk: 1050, delay: "8–12 jours", zone: "Sud", communes: c("In Guezzam", "Tin Zaouatine") },
  { code: "55", name: "Touggourt", home: 750, stopdesk: 550, delay: "4–6 jours", zone: "Sud", communes: c("Touggourt", "Témacine", "Megarine") },
  { code: "56", name: "Djanet", home: 1300, stopdesk: 980, delay: "7–10 jours", zone: "Sud", communes: c("Djanet", "Bordj El Haouas") },
  { code: "57", name: "El M'Ghair", home: 750, stopdesk: 550, delay: "4–6 jours", zone: "Sud", communes: c("El M'Ghair", "Djamaa", "Still") },
  { code: "58", name: "El Meniaa", home: 850, stopdesk: 620, delay: "5–7 jours", zone: "Sud", communes: c("El Meniaa", "Hassi Gara", "Hassi Fehal") },
  { code: "59", name: "Aflou", home: 700, stopdesk: 500, delay: "3–5 jours", zone: "Hauts Plateaux", communes: c("Aflou", "Sebgag", "Sidi Bouzid") },
  { code: "60", name: "Barika", home: 650, stopdesk: 470, delay: "2–4 jours", zone: "Hauts Plateaux", communes: c("Barika", "Bitam", "M'doukal") },
  { code: "61", name: "El Kantara", home: 650, stopdesk: 480, delay: "3–4 jours", zone: "Est", communes: c("El Kantara", "Aïn Zaatout", "El Outaya") },
  { code: "62", name: "Bir El Ater", home: 700, stopdesk: 520, delay: "3–5 jours", zone: "Est", communes: c("Bir El Ater", "Ogla Melha", "El Ogla") },
  { code: "63", name: "El Aricha", home: 700, stopdesk: 500, delay: "3–5 jours", zone: "Ouest", communes: c("El Aricha", "Sidi Djilali", "Sebdou") },
  { code: "64", name: "Ksar Chellala", home: 650, stopdesk: 480, delay: "3–4 jours", zone: "Hauts Plateaux", communes: c("Ksar Chellala", "Zmalet El Emir Abdelkader", "Serghine") },
  { code: "65", name: "Aïn Oussara", home: 600, stopdesk: 450, delay: "2–4 jours", zone: "Hauts Plateaux", communes: c("Aïn Oussara", "Aïn El Ibel", "Guernini") },
  { code: "66", name: "Messaad", home: 700, stopdesk: 520, delay: "3–5 jours", zone: "Sud", communes: c("Messaad", "Sed Rahal", "Deldoul") },
  { code: "67", name: "Ksar El Boukhari", home: 550, stopdesk: 400, delay: "2–3 jours", zone: "Centre", communes: c("Ksar El Boukhari", "Aziz", "Ouled Antar") },
  { code: "68", name: "Bou Saâda", home: 650, stopdesk: 480, delay: "2–4 jours", zone: "Hauts Plateaux", communes: c("Bou Saâda", "Ouled Sidi Brahim", "El Hamel") },
  { code: "69", name: "El Abiodh Sidi Cheikh", home: 850, stopdesk: 620, delay: "4–6 jours", zone: "Sud", communes: c("El Abiodh Sidi Cheikh", "Aïn El Orak", "Arbaouat") },
];

export function getWilaya(code: string) {
  return wilayas.find((w) => w.code === code);
}
